### ISSUE TITLE
Intermittent spec failure on Travis build:  Ldp:Conflict

### ISSUE THREAD

**Issue by val99erie** [curationexperts/cypripedium#273]
```
Failures:
  1) WorkZip#create_zip a work file attached files creates a zip with the files
     Failure/Error: File.open(file_fixture('pdf-sample.pdf')) { |file| create(:file_set, content: file) }
     Ldp::Conflict:
       Can't call create on an existing resource
     # ./spec/models/work_zip_spec.rb:10:in `block (3 levels) in <top (required)>'
     # ./spec/models/work_zip_spec.rb:10:in `open'
     # ./spec/models/work_zip_spec.rb:10:in `block (2 levels) in <top (required)>'
     # ./spec/models/work_zip_spec.rb:18:in `block (2 levels) in <top (required)>'
     # ./spec/models/work_zip_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/models/work_zip_spec.rb:31:in `block (4 levels) in <top (required)>'
Finished in 3 minutes 20.7 seconds (files took 31.85 seconds to load)
154 examples, 1 failure
Failed examples:
rspec ./spec/models/work_zip_spec.rb:30 # WorkZip#create_zip a work file attached files creates a zip with the files
Randomized with seed 22157
```

**Comment by val99erie** [comment]
```
     Ldp::Conflict:
       Can't call create on an existing resource
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/ldp-0.7.2/lib/ldp/resource.rb:82:in `create'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/ldp-0.7.2/lib/ldp/resource/rdf_source.rb:20:in `create'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/active-fedora-11.5.4/lib/active_fedora/persistence.rb:180:in `_create_record'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/active-fedora-11.5.4/lib/active_fedora/indexing.rb:64:in `_create_record'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/active-fedora-11.5.4/lib/active_fedora/callbacks.rb:240:in `block in _create_record'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/active-fedora-11.5.4/lib/active_fedora/callbacks.rb:240:in `_create_record'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/active-fedora-11.5.4/lib/active_fedora/persistence.rb:172:in `create_or_update'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/active-fedora-11.5.4/lib/active_fedora/callbacks.rb:236:in `block in create_or_update'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/active-fedora-11.5.4/lib/active_fedora/callbacks.rb:236:in `create_or_update'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/active-fedora-11.5.4/lib/active_fedora/persistence.rb:37:in `save!'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/active-fedora-11.5.4/lib/active_fedora/validations.rb:56:in `save!'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/active-fedora-11.5.4/lib/active_fedora/associations/builder/orders.rb:50:in `save!'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/factory_bot-4.11.1/lib/factory_bot/configuration.rb:18:in `block in initialize'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/factory_bot-4.11.1/lib/factory_bot/evaluation.rb:18:in `create'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/factory_bot-4.11.1/lib/factory_bot/strategy/create.rb:12:in `block in result'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/factory_bot-4.11.1/lib/factory_bot/strategy/create.rb:9:in `tap'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/factory_bot-4.11.1/lib/factory_bot/strategy/create.rb:9:in `result'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/factory_bot-4.11.1/lib/factory_bot/factory.rb:43:in `run'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/factory_bot-4.11.1/lib/factory_bot/factory_runner.rb:29:in `block in run'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/factory_bot-4.11.1/lib/factory_bot/factory_runner.rb:28:in `run'
     # /Users/valerie/.rvm/gems/ruby-2.4.2@fed/gems/factory_bot-4.11.1/lib/factory_bot/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./spec/models/work_zip_spec.rb:19:in `block (2 levels) in <top (required)>'
     # ./spec/models/work_zip_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/models/work_zip_spec.rb:74:in `block (3 levels) in <top (required)>'
     # ./spec/models/work_zip_spec.rb:84:in `block (4 levels) in <top (required)>'
```
