### ISSUE TITLE
Upgrade active-fedora

### ISSUE THREAD

**Issue by bess** [curationexperts/cypripedium#381]
When attempting to upgrade gems on cypripedium, we're hitting a bug caused by a changed predicate. 

Error looks like this:

```

An error occurred while loading ./spec/hyrax/actors/conference_proceeding_actor_spec.rb.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

NoMethodError:
  undefined method `filename' for #<Class:0x00007fca068c2170>
  Did you mean?  fileSize
# /Users/bess/.rvm/gems/ruby-2.6.3@cypripedium/gems/active-fedora-11.5.5/lib/active_fedora/with_metadata/default_schema.rb:7:in `<class:DefaultSchema>'
# /Users/bess/.rvm/gems/ruby-2.6.3@cypripedium/gems/active-fedora-11.5.5/lib/active_fedora/with_metadata/default_schema.rb:5:in `<module:WithMetadata>'
```

The relevant line in `active-fedora` is:
`property :file_name, predicate: ::RDF::Vocab::EBUCore.filename`

This has been fixed in some versions of active-fedora: https://github.com/samvera/active_fedora/pull/1421

- [x] ~Upgrade this application to use a more recent version of active-fedora and perform whatever data migration is necessary to update all our references to the outdated RDF term~
- [x] Pin the application to rdf-vocab < 3.1.5

**Comment by bess** [comment]
Collin says: @bess if you pin to rdf-vocab to < 3.1.5, you can avoid the change
